apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: testpod
      image: smarticu5/container-review-admin
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /host
          name: noderoot
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      resources:
        limits:
          memory: 1024Mi
          cpu: 400m
        requests:
          memory: 512Mi
          cpu: 400m
  volumes:
    - name: noderoot
      hostPath:
        path: /